### ISSUE TITLE
Not accepting STT results with a confidence below a certain level

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.server#19]
The server should fail on STT results below a certain confidence level.

**Comment by tilmankamp** [comment]
@andrenatal : I think I am going to implement a minimum confidence config-value per provider (google/watson/kaldi). As you brought this up: Do you happen to know a certain provider that should be capped by a certain value?

**Comment by andrenatal** [comment]
@tilmankamp That varies per engine and how good their models are. 

For kaldi I know they have different scores for language and acoustic model. While we were testing it, I got pretty wrong results with scores around .99 :( 

For google, I'd remove utterances below 0.7, but we need to do more testing to see if this is accurate. 

Maybe with the tests that @kdavis-mozilla is doing with real speech corpora you can get a proper threshold.

**Comment by kdavis-mozilla** [comment]
I'm not retaining confidence levels, but I can modify the tool to do so. It'd be interesting to see how confidence levels and WER relate to one another.

**Comment by andrenatal** [comment]
@kdavis-mozilla Agreed. That would be an interesting test to do.
