### ISSUE TITLE
The onClose from watson event is never being called

### ISSUE THREAD

**Issue by andrenatal** [mozilla/vaani.server#3]
The voice.on('close', https://github.com/mozilla/vaani.server/blob/master/index.js#L109 is bever being called by the watson api.

**Comment by kdavis-mozilla** [comment]
@andrenatal Can you test this to make sure this solves your problem. It seems to work for me.

**Comment by tilmankamp** [comment]
LGTM - but Andre should check...

**Comment by kdavis-mozilla** [comment]
@andrenatal Did you test this yet?

**Comment by andrenatal** [comment]
Give me few minutes please

**Comment by andrenatal** [comment]
@kdavis-mozilla I just updated my server repo and the client stopped working. I don't know if it's related with the onEnd, will start to investigate.

**Comment by andrenatal** [comment]
@kdavis-mozilla Neither the current client code that used to work, neither the test is working with the latest server code on my end. This is the test result:

> vaani.server@0.0.1 test /Users/anatal/projects/mozilla/vaani-iot/vaani.server
> node test/tests.js Add marmalade to my shopping list.

loading cached parser...
Sending answer: 100 - Sorry, the service is not available at the moment.
{ status: 100,
  message: 'Sorry, the service is not available at the moment.',
  command: '<unknown>',
  confidence: 1 }

npm ERR! Test failed.  See above for more details.

**Comment by andrenatal** [comment]
But I can see that: voice.on('end', is being called. 

So I'm closing this.
