### ISSUE TITLE
Server added: 'a' to my shopping list

### ISSUE THREAD

**Issue by andrenatal** [mozilla/vaani.server#6]
I got this from the server:

{"status":0,"message":"Added a to your shopping list.","command":"a.","confidence":0.5766686189918435}

**Comment by kdavis-mozilla** [comment]
It thought you said the letter "a". So it added "a", interpreted as the vitamin A, to your list.

You can add items by just saying the item's name. So, for example, you can add milk by simply saying "Milk".
